### ISSUE TITLE
Tool type not found

### ISSUE THREAD

**Issue by tree1891** [wwh1004/ToolLoader#1]
`Unhandled Exception: System.InvalidOperationException: Tool type not found
   at Tool.Loader.Loader.CreateToolInstance(Assembly assembly, Type& optionsType) in C:\projects\toolloader\Tool.Loader\Loader.CLR.cs:line 130
   at Tool.Loader.Loader.Execute(String[] args) in C:\projects\toolloader\Tool.Loader\Loader.CLR.cs:line 48
   at Tool.Loader.CLR40.x86.Program.Main(String[] args) in C:\projects\toolloader\Tool.Loader.CLR40.x86\Program.cs:line 5`

**Comment by wwh1004** [comment]
Tool.Loader.*.exe <tool-name.dll> <arguments>

Which loader version and which tool? they should be matched.

**Comment by tree1891** [comment]
Tool.Loader.Auto.exe ConfuserExKiller.dll -f <packed.dll>

**Comment by wwh1004** [comment]
maybe you should use older tool loader. the confuserex tools uses an old tool.interface.dll
